---
version: "2"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://localhost:8080
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=mydatabasepassword
      - DB_DATABASE=bookstackapp
    volumes:  
      - ./bookstack:/config
    restart: unless-stopped
    depends_on:
      - bookstack_db
    networks:
      - web
    ports:
      - 8080:80
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=mysecretrootpassword
      - TZ=America/Denver
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=mydatabasepassword
    volumes:
      - ./database:/config
    restart: unless-stopped
    networks:
      - web
networks:
  web:
    external: true